[package]
name = "ramen-os"
version = "0.1.0"
edition = "2024"

[dependencies]
heapless = "0.8.0"
limine = "0.4"

[features]
test-mode = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
